config/routes.rb
Rails.application.routes.draw do
  resources :stores
  get "listing" => "products#listing"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def listing
        @products = Product.includes(:store)
        # @products = Product.where(store_id: 2).includes(:store)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(@store), notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to store_url(@store), notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy!

    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Delivery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/listing.html.erb
<h1>Product Listing</h1>

<div>
    <% @products.each do |product| %>
    <div>
        <h3><%= product.title %></h3>
        <p>Store: <%= product.store.name %></p>

    </div>
    <hr />
    <% end %>
</div>

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/_store.html.erb
<div id="<%= dom_id store %>">
  <p>
    <strong>Name:</strong>
    <%= store.name %>
  </p>

</div>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Show this store", @store %> |
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stores</h1>

<div id="stores">
  <% @stores.each do |store| %>
    <%= render store %>
    <p>
      <%= link_to "Show this store", store %>
    </p>
  <% end %>
</div>

<%= link_to "New store", new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @store %>

<div>
  <%= link_to "Edit this store", edit_store_path(@store) %> |
  <%= link_to "Back to stores", stores_path %>

  <%= button_to "Destroy this store", @store, method: :delete %>
</div>